-- Telescope picker for Noto Color Emoji / Unicode emoji
-- Fuzzy searchable by keywords, inserts at cursor on selection
--
-- Usage: require('emoji_picker').pick()
-- Keymap: <leader>fi (Find Icons)

local M = {}

-- Comprehensive emoji dataset: { emoji, name, keywords }
-- These are standard Unicode emoji that render via Noto Color Emoji font
local emojis = {
  -- Smileys & Emotion
  { "😀", "grinning face", "smile happy grin" },
  { "😃", "grinning face with big eyes", "smile happy joy" },
  { "😄", "grinning face with smiling eyes", "smile happy joy laugh" },
  { "😁", "beaming face with smiling eyes", "smile happy grin" },
  { "😆", "grinning squinting face", "laugh happy satisfied" },
  { "😅", "grinning face with sweat", "smile hot relief nervous" },
  { "🤣", "rolling on the floor laughing", "laugh lol rofl funny" },
  { "😂", "face with tears of joy", "laugh cry happy tears funny" },
  { "🙂", "slightly smiling face", "smile" },
  { "🙃", "upside-down face", "sarcasm silly irony" },
  { "😉", "winking face", "wink flirt" },
  { "😊", "smiling face with smiling eyes", "smile happy blush" },
  { "😇", "smiling face with halo", "angel innocent" },
  { "🥰", "smiling face with hearts", "love adore crush" },
  { "😍", "smiling face with heart-eyes", "love crush heart" },
  { "🤩", "star-struck", "star eyes wow amazing" },
  { "😘", "face blowing a kiss", "kiss love flirt" },
  { "😗", "kissing face", "kiss love" },
  { "😚", "kissing face with closed eyes", "kiss love" },
  { "😙", "kissing face with smiling eyes", "kiss love" },
  { "🥲", "smiling face with tear", "sad happy grateful" },
  { "😋", "face savoring food", "yummy delicious tongue" },
  { "😛", "face with tongue", "tongue silly playful" },
  { "😜", "winking face with tongue", "tongue silly wink" },
  { "🤪", "zany face", "crazy silly wild goofy" },
  { "😝", "squinting face with tongue", "tongue silly" },
  { "🤑", "money-mouth face", "money rich dollar" },
  { "🤗", "hugging face", "hug warm" },
  { "🤭", "face with hand over mouth", "oops giggle shy" },
  { "🤫", "shushing face", "quiet silence secret" },
  { "🤔", "thinking face", "think hmm consider" },
  { "🤐", "zipper-mouth face", "secret quiet shut" },
  { "🤨", "face with raised eyebrow", "skeptic suspicious doubt" },
  { "😐", "neutral face", "meh indifferent" },
  { "😑", "expressionless face", "blank meh" },
  { "😶", "face without mouth", "silence quiet speechless" },
  { "😏", "smirking face", "smirk sly" },
  { "😒", "unamused face", "bored annoyed" },
  { "🙄", "face with rolling eyes", "eyeroll annoyed whatever" },
  { "😬", "grimacing face", "awkward nervous cringe" },
  { "🤥", "lying face", "pinocchio lie" },
  { "😌", "relieved face", "calm peace" },
  { "😔", "pensive face", "sad thoughtful" },
  { "😪", "sleepy face", "tired sleep" },
  { "🤤", "drooling face", "drool hungry" },
  { "😴", "sleeping face", "sleep zzz tired" },
  { "😷", "face with medical mask", "sick mask covid" },
  { "🤒", "face with thermometer", "sick fever ill" },
  { "🤕", "face with head-bandage", "hurt injured clumsy" },
  { "🤢", "nauseated face", "sick vomit gross" },
  { "🤮", "face vomiting", "sick puke throw up" },
  { "🥵", "hot face", "heat sweating" },
  { "🥶", "cold face", "frozen freezing ice" },
  { "🥴", "woozy face", "dizzy drunk tipsy" },
  { "😵", "face with crossed-out eyes", "dead dizzy" },
  { "😵‍💫", "face with spiral eyes", "dizzy hypnotized" },
  { "🤯", "exploding head", "mind blown shocked" },
  { "🤠", "cowboy hat face", "cowboy western" },
  { "🥳", "partying face", "party celebrate birthday" },
  { "🥸", "disguised face", "disguise incognito" },
  { "😎", "smiling face with sunglasses", "cool sunglasses" },
  { "🤓", "nerd face", "nerd geek glasses" },
  { "🧐", "face with monocle", "classy detective" },
  { "😕", "confused face", "confused puzzled" },
  { "😟", "worried face", "worried concerned nervous" },
  { "🙁", "slightly frowning face", "sad frown" },
  { "😮", "face with open mouth", "surprised shocked wow" },
  { "😯", "hushed face", "surprised quiet wow" },
  { "😲", "astonished face", "shocked surprised amazed" },
  { "😳", "flushed face", "blush embarrassed" },
  { "🥺", "pleading face", "puppy eyes please beg" },
  { "😦", "frowning face with open mouth", "sad aw" },
  { "😧", "anguished face", "stunned pain" },
  { "😨", "fearful face", "scared fear afraid" },
  { "😰", "anxious face with sweat", "nervous worried" },
  { "😥", "sad but relieved face", "phew disappointed" },
  { "😢", "crying face", "sad cry tear" },
  { "😭", "loudly crying face", "sob cry tears" },
  { "😱", "face screaming in fear", "scream scared horror" },
  { "😖", "confounded face", "confused frustrated" },
  { "😣", "persevering face", "struggle tough" },
  { "😞", "disappointed face", "sad sorry" },
  { "😓", "downcast face with sweat", "hot frustrated" },
  { "😩", "weary face", "tired frustrated" },
  { "😫", "tired face", "exhausted sleepy" },
  { "🥱", "yawning face", "yawn tired bored sleepy" },
  { "😤", "face with steam from nose", "angry triumph" },
  { "😡", "pouting face", "angry rage mad" },
  { "😠", "angry face", "angry mad" },
  { "🤬", "face with symbols on mouth", "swearing cursing angry" },
  { "😈", "smiling face with horns", "devil evil purple" },
  { "👿", "angry face with horns", "devil evil imp" },
  { "💀", "skull", "death dead skeleton" },
  { "☠️", "skull and crossbones", "death danger poison" },
  { "💩", "pile of poo", "poop shit" },
  { "🤡", "clown face", "clown joker" },
  { "👹", "ogre", "monster scary" },
  { "👺", "goblin", "monster red" },
  { "👻", "ghost", "halloween spooky" },
  { "👽", "alien", "ufo space extraterrestrial" },
  { "👾", "alien monster", "game space invader" },
  { "🤖", "robot", "bot machine ai" },
  { "😺", "grinning cat", "cat smile" },
  { "😸", "grinning cat with smiling eyes", "cat smile" },
  { "😹", "cat with tears of joy", "cat laugh" },
  { "😻", "smiling cat with heart-eyes", "cat love" },
  { "😼", "cat with wry smile", "cat smirk" },
  { "😽", "kissing cat", "cat kiss" },
  { "🙀", "weary cat", "cat scared" },
  { "😿", "crying cat", "cat sad tear" },
  { "😾", "pouting cat", "cat angry" },
  { "🙈", "see-no-evil monkey", "monkey eyes blind" },
  { "🙉", "hear-no-evil monkey", "monkey ears deaf" },
  { "🙊", "speak-no-evil monkey", "monkey mouth mute" },

  -- Hearts & Emotions
  { "💋", "kiss mark", "kiss lips love" },
  { "💌", "love letter", "letter heart love mail" },
  { "💘", "heart with arrow", "love cupid valentine" },
  { "💝", "heart with ribbon", "love gift valentine" },
  { "💖", "sparkling heart", "love shine" },
  { "💗", "growing heart", "love pink" },
  { "💓", "beating heart", "love heartbeat" },
  { "💞", "revolving hearts", "love" },
  { "💕", "two hearts", "love pair" },
  { "💟", "heart decoration", "love purple" },
  { "❣️", "heart exclamation", "love" },
  { "💔", "broken heart", "sad breakup" },
  { "❤️‍🔥", "heart on fire", "love passion" },
  { "❤️‍🩹", "mending heart", "heal recover" },
  { "❤️", "red heart", "love red" },
  { "🧡", "orange heart", "love orange" },
  { "💛", "yellow heart", "love yellow friendship" },
  { "💚", "green heart", "love green" },
  { "💙", "blue heart", "love blue" },
  { "💜", "purple heart", "love purple" },
  { "🖤", "black heart", "love dark" },
  { "🤍", "white heart", "love pure" },
  { "🤎", "brown heart", "love brown" },
  { "💯", "hundred points", "100 perfect score" },
  { "💢", "anger symbol", "angry" },
  { "💥", "collision", "boom crash explosion bang" },
  { "💫", "dizzy", "star sparkle" },
  { "💦", "sweat droplets", "water splash" },
  { "💨", "dashing away", "wind fast running" },
  { "🕳️", "hole", "void" },
  { "💣", "bomb", "explosive danger" },
  { "💬", "speech balloon", "chat comment bubble talk" },
  { "💭", "thought balloon", "think bubble" },
  { "💤", "zzz", "sleep tired" },

  -- Hands & Gestures
  { "👋", "waving hand", "wave hello goodbye" },
  { "🤚", "raised back of hand", "hand" },
  { "🖐️", "hand with fingers splayed", "hand five" },
  { "✋", "raised hand", "stop hand high five" },
  { "🖖", "vulcan salute", "spock star trek" },
  { "👌", "ok hand", "ok okay perfect" },
  { "🤌", "pinched fingers", "italian what" },
  { "🤏", "pinching hand", "small tiny little" },
  { "✌️", "victory hand", "peace victory two" },
  { "🤞", "crossed fingers", "luck hope" },
  { "🤟", "love-you gesture", "love rock" },
  { "🤘", "sign of the horns", "rock metal" },
  { "🤙", "call me hand", "call phone hang loose" },
  { "👈", "backhand index pointing left", "left point" },
  { "👉", "backhand index pointing right", "right point" },
  { "👆", "backhand index pointing up", "up point" },
  { "🖕", "middle finger", "finger rude" },
  { "👇", "backhand index pointing down", "down point" },
  { "☝️", "index pointing up", "up point" },
  { "👍", "thumbs up", "approve like yes good" },
  { "👎", "thumbs down", "disapprove dislike no bad" },
  { "✊", "raised fist", "fist power" },
  { "👊", "oncoming fist", "punch fist bump" },
  { "🤛", "left-facing fist", "fist bump" },
  { "🤜", "right-facing fist", "fist bump" },
  { "👏", "clapping hands", "clap applause bravo" },
  { "🙌", "raising hands", "celebration hooray praise" },
  { "👐", "open hands", "hands" },
  { "🤲", "palms up together", "prayer" },
  { "🤝", "handshake", "shake deal agreement" },
  { "🙏", "folded hands", "pray please thanks namaste" },
  { "✍️", "writing hand", "write" },
  { "💅", "nail polish", "beauty nails" },
  { "🤳", "selfie", "camera phone" },
  { "💪", "flexed biceps", "strong muscle arm" },

  -- People
  { "👶", "baby", "child infant" },
  { "👧", "girl", "female child" },
  { "🧒", "child", "kid" },
  { "👦", "boy", "male child" },
  { "👩", "woman", "female" },
  { "🧑", "person", "adult" },
  { "👨", "man", "male" },
  { "👩‍🦱", "woman curly hair", "woman curly" },
  { "👨‍🦱", "man curly hair", "man curly" },
  { "👩‍🦰", "woman red hair", "woman ginger" },
  { "👨‍🦰", "man red hair", "man ginger" },
  { "👱‍♀️", "woman blond hair", "woman blonde" },
  { "👱‍♂️", "man blond hair", "man blonde" },
  { "👩‍🦳", "woman white hair", "woman old grey" },
  { "👨‍🦳", "man white hair", "man old grey" },
  { "👩‍🦲", "woman bald", "woman" },
  { "👨‍🦲", "man bald", "man" },
  { "🧔", "person beard", "beard" },
  { "👵", "old woman", "grandmother grandma" },
  { "🧓", "older person", "elder" },
  { "👴", "old man", "grandfather grandpa" },

  -- Animals & Nature
  { "🐵", "monkey face", "monkey primate" },
  { "🐒", "monkey", "primate" },
  { "🦍", "gorilla", "ape primate" },
  { "🦧", "orangutan", "ape primate" },
  { "🐶", "dog face", "dog pet puppy" },
  { "🐕", "dog", "pet" },
  { "🦮", "guide dog", "service blind" },
  { "🐩", "poodle", "dog fancy" },
  { "🐺", "wolf", "wild" },
  { "🦊", "fox", "wild cunning" },
  { "🦝", "raccoon", "bandit" },
  { "🐱", "cat face", "cat pet kitty" },
  { "🐈", "cat", "pet" },
  { "🐈‍⬛", "black cat", "cat dark" },
  { "🦁", "lion", "king jungle" },
  { "🐯", "tiger face", "tiger wild" },
  { "🐅", "tiger", "wild" },
  { "🐆", "leopard", "wild spots" },
  { "🐴", "horse face", "horse" },
  { "🐎", "horse", "racing" },
  { "🦄", "unicorn", "magic fantasy horn" },
  { "🦓", "zebra", "stripes" },
  { "🦌", "deer", "antler bambi" },
  { "🦬", "bison", "buffalo" },
  { "🐮", "cow face", "cow moo" },
  { "🐂", "ox", "bull" },
  { "🐃", "water buffalo", "buffalo" },
  { "🐄", "cow", "farm" },
  { "🐷", "pig face", "pig oink" },
  { "🐖", "pig", "farm" },
  { "🐗", "boar", "wild pig" },
  { "🐽", "pig nose", "nose" },
  { "🐏", "ram", "sheep horn" },
  { "🐑", "ewe", "sheep lamb" },
  { "🐐", "goat", "farm" },
  { "🐪", "camel", "desert hump" },
  { "🐫", "two-hump camel", "desert" },
  { "🦙", "llama", "alpaca" },
  { "🦒", "giraffe", "tall spots" },
  { "🐘", "elephant", "big trunk" },
  { "🦣", "mammoth", "prehistoric extinct" },
  { "🦏", "rhinoceros", "horn" },
  { "🦛", "hippopotamus", "hippo" },
  { "🐭", "mouse face", "mouse rodent" },
  { "🐁", "mouse", "rodent" },
  { "🐀", "rat", "rodent" },
  { "🐹", "hamster", "pet rodent" },
  { "🐰", "rabbit face", "bunny easter" },
  { "🐇", "rabbit", "bunny" },
  { "🐿️", "chipmunk", "squirrel" },
  { "🦫", "beaver", "dam" },
  { "🦔", "hedgehog", "spiky" },
  { "🦇", "bat", "vampire night" },
  { "🐻", "bear", "brown grizzly" },
  { "🐻‍❄️", "polar bear", "arctic ice white" },
  { "🐨", "koala", "australia" },
  { "🐼", "panda", "bamboo china" },
  { "🦥", "sloth", "lazy slow" },
  { "🦦", "otter", "cute water" },
  { "🦨", "skunk", "stink" },
  { "🦘", "kangaroo", "australia jump pouch" },
  { "🦡", "badger", "honey" },
  { "🐾", "paw prints", "pet animal track" },
  { "🦃", "turkey", "thanksgiving" },
  { "🐔", "chicken", "farm bird" },
  { "🐓", "rooster", "cock bird" },
  { "🐣", "hatching chick", "baby bird" },
  { "🐤", "baby chick", "bird" },
  { "🐥", "front-facing baby chick", "bird" },
  { "🐦", "bird", "tweet" },
  { "🐧", "penguin", "arctic cold" },
  { "🕊️", "dove", "peace" },
  { "🦅", "eagle", "bird america" },
  { "🦆", "duck", "bird quack" },
  { "🦢", "swan", "bird grace" },
  { "🦉", "owl", "bird wise night" },
  { "🦤", "dodo", "extinct bird" },
  { "🪶", "feather", "bird light" },
  { "🦩", "flamingo", "bird pink" },
  { "🦚", "peacock", "bird pretty" },
  { "🦜", "parrot", "bird talk" },
  { "🐸", "frog", "toad ribbit" },
  { "🐊", "crocodile", "gator reptile" },
  { "🐢", "turtle", "slow shell" },
  { "🦎", "lizard", "reptile" },
  { "🐍", "snake", "reptile" },
  { "🐲", "dragon face", "dragon fantasy" },
  { "🐉", "dragon", "fantasy" },
  { "🦕", "sauropod", "dinosaur brontosaurus" },
  { "🦖", "t-rex", "dinosaur tyrannosaurus" },
  { "🐳", "spouting whale", "whale ocean" },
  { "🐋", "whale", "ocean sea" },
  { "🐬", "dolphin", "ocean sea" },
  { "🦭", "seal", "ocean" },
  { "🐟", "fish", "ocean sea" },
  { "🐠", "tropical fish", "ocean nemo" },
  { "🐡", "blowfish", "ocean puffer" },
  { "🦈", "shark", "ocean danger" },
  { "🐙", "octopus", "ocean tentacle" },
  { "🐚", "spiral shell", "shell beach ocean" },
  { "🐌", "snail", "slow shell" },
  { "🦋", "butterfly", "insect pretty" },
  { "🐛", "bug", "insect caterpillar" },
  { "🐜", "ant", "insect" },
  { "🐝", "honeybee", "bee insect honey" },
  { "🪲", "beetle", "insect bug" },
  { "🐞", "lady beetle", "ladybug insect" },
  { "🦗", "cricket", "insect" },
  { "🪳", "cockroach", "insect bug" },
  { "🕷️", "spider", "insect web" },
  { "🕸️", "spider web", "web" },
  { "🦂", "scorpion", "danger" },
  { "🦟", "mosquito", "insect bite" },
  { "🪰", "fly", "insect bug" },
  { "🪱", "worm", "insect" },
  { "🦠", "microbe", "germ bacteria virus" },

  -- Plants & Flowers
  { "💐", "bouquet", "flowers gift" },
  { "🌸", "cherry blossom", "flower spring pink japan" },
  { "💮", "white flower", "flower" },
  { "🏵️", "rosette", "flower award" },
  { "🌹", "rose", "flower love red" },
  { "🥀", "wilted flower", "dead sad" },
  { "🌺", "hibiscus", "flower tropical" },
  { "🌻", "sunflower", "flower yellow sun" },
  { "🌼", "blossom", "flower yellow" },
  { "🌷", "tulip", "flower spring" },
  { "🌱", "seedling", "plant grow sprout" },
  { "🪴", "potted plant", "plant house" },
  { "🌲", "evergreen tree", "tree pine christmas" },
  { "🌳", "deciduous tree", "tree" },
  { "🌴", "palm tree", "tropical beach" },
  { "🌵", "cactus", "desert plant" },
  { "🌾", "sheaf of rice", "rice wheat grain" },
  { "🌿", "herb", "plant leaf green" },
  { "☘️", "shamrock", "clover irish" },
  { "🍀", "four leaf clover", "luck irish" },
  { "🍁", "maple leaf", "fall autumn canada" },
  { "🍂", "fallen leaf", "fall autumn" },
  { "🍃", "leaf fluttering in wind", "nature wind" },
  { "🪹", "empty nest", "bird home" },
  { "🪺", "nest with eggs", "bird home" },
  { "🍄", "mushroom", "fungus" },

  -- Food & Drink
  { "🍇", "grapes", "fruit wine purple" },
  { "🍈", "melon", "fruit" },
  { "🍉", "watermelon", "fruit summer" },
  { "🍊", "tangerine", "fruit orange citrus" },
  { "🍋", "lemon", "fruit yellow citrus sour" },
  { "🍌", "banana", "fruit yellow" },
  { "🍍", "pineapple", "fruit tropical" },
  { "🥭", "mango", "fruit tropical" },
  { "🍎", "red apple", "fruit" },
  { "🍏", "green apple", "fruit" },
  { "🍐", "pear", "fruit" },
  { "🍑", "peach", "fruit" },
  { "🍒", "cherries", "fruit cherry" },
  { "🍓", "strawberry", "fruit berry" },
  { "🫐", "blueberries", "fruit berry" },
  { "🥝", "kiwi fruit", "fruit" },
  { "🍅", "tomato", "vegetable fruit" },
  { "🫒", "olive", "food mediterranean" },
  { "🥥", "coconut", "tropical" },
  { "🥑", "avocado", "fruit food" },
  { "🍆", "eggplant", "vegetable aubergine" },
  { "🥔", "potato", "vegetable food" },
  { "🥕", "carrot", "vegetable orange food" },
  { "🌽", "ear of corn", "corn vegetable food" },
  { "🌶️", "hot pepper", "spicy chili" },
  { "🫑", "bell pepper", "vegetable food" },
  { "🥒", "cucumber", "vegetable food" },
  { "🥬", "leafy green", "vegetable salad lettuce" },
  { "🥦", "broccoli", "vegetable green food" },
  { "🧄", "garlic", "food cooking" },
  { "🧅", "onion", "food cooking" },
  { "🍞", "bread", "food toast" },
  { "🥐", "croissant", "bread french pastry" },
  { "🥖", "baguette bread", "french food" },
  { "🫓", "flatbread", "food" },
  { "🥨", "pretzel", "food snack" },
  { "🥯", "bagel", "food bread" },
  { "🥞", "pancakes", "breakfast food" },
  { "🧇", "waffle", "breakfast food" },
  { "🧀", "cheese wedge", "cheese food" },
  { "🍖", "meat on bone", "meat food" },
  { "🍗", "poultry leg", "chicken food" },
  { "🥩", "cut of meat", "steak food" },
  { "🥓", "bacon", "food breakfast" },
  { "🍔", "hamburger", "burger food fast food" },
  { "🍟", "french fries", "fries food fast food" },
  { "🍕", "pizza", "food italian" },
  { "🌭", "hot dog", "food" },
  { "🥪", "sandwich", "food bread" },
  { "🌮", "taco", "food mexican" },
  { "🌯", "burrito", "food mexican wrap" },
  { "🫔", "tamale", "food mexican" },
  { "🥙", "stuffed flatbread", "food pita" },
  { "🧆", "falafel", "food" },
  { "🥚", "egg", "food breakfast" },
  { "🍳", "cooking", "egg frying pan breakfast" },
  { "🥘", "shallow pan of food", "paella food" },
  { "🍲", "pot of food", "stew soup" },
  { "🫕", "fondue", "food cheese" },
  { "🥣", "bowl with spoon", "cereal food" },
  { "🥗", "green salad", "salad food healthy" },
  { "🍿", "popcorn", "snack movie" },
  { "🧈", "butter", "food" },
  { "🧂", "salt", "food seasoning" },
  { "🥫", "canned food", "food" },
  { "🍱", "bento box", "japanese food" },
  { "🍘", "rice cracker", "japanese food" },
  { "🍙", "rice ball", "japanese food onigiri" },
  { "🍚", "cooked rice", "food" },
  { "🍛", "curry rice", "food indian" },
  { "🍜", "steaming bowl", "noodles ramen pho soup" },
  { "🍝", "spaghetti", "pasta italian food" },
  { "🍠", "roasted sweet potato", "food" },
  { "🍢", "oden", "japanese food" },
  { "🍣", "sushi", "japanese food fish" },
  { "🍤", "fried shrimp", "tempura food" },
  { "🍥", "fish cake with swirl", "japanese food" },
  { "🥮", "moon cake", "chinese food" },
  { "🍡", "dango", "japanese food" },
  { "🥟", "dumpling", "food chinese" },
  { "🥠", "fortune cookie", "food chinese" },
  { "🥡", "takeout box", "food chinese" },
  { "🦀", "crab", "seafood" },
  { "🦞", "lobster", "seafood" },
  { "🦐", "shrimp", "seafood prawn" },
  { "🦑", "squid", "seafood" },
  { "🦪", "oyster", "seafood pearl" },
  { "🍦", "soft ice cream", "icecream dessert" },
  { "🍧", "shaved ice", "dessert" },
  { "🍨", "ice cream", "dessert" },
  { "🍩", "doughnut", "donut dessert" },
  { "🍪", "cookie", "dessert biscuit" },
  { "🎂", "birthday cake", "cake birthday dessert" },
  { "🍰", "shortcake", "cake dessert" },
  { "🧁", "cupcake", "dessert cake" },
  { "🥧", "pie", "dessert food" },
  { "🍫", "chocolate bar", "chocolate dessert candy" },
  { "🍬", "candy", "sweet dessert" },
  { "🍭", "lollipop", "candy sweet dessert" },
  { "🍮", "custard", "dessert pudding" },
  { "🍯", "honey pot", "honey sweet" },
  { "🍼", "baby bottle", "milk baby" },
  { "🥛", "glass of milk", "milk drink" },
  { "☕", "hot beverage", "coffee tea drink" },
  { "🫖", "teapot", "tea drink" },
  { "🍵", "teacup without handle", "tea drink" },
  { "🍶", "sake", "japanese drink alcohol" },
  { "🍾", "bottle with popping cork", "champagne celebrate" },
  { "🍷", "wine glass", "wine drink alcohol" },
  { "🍸", "cocktail glass", "drink alcohol martini" },
  { "🍹", "tropical drink", "cocktail drink alcohol" },
  { "🍺", "beer mug", "beer drink alcohol" },
  { "🍻", "clinking beer mugs", "beer drink cheers" },
  { "🥂", "clinking glasses", "cheers celebrate toast" },
  { "🥃", "tumbler glass", "whiskey drink alcohol" },
  { "🥤", "cup with straw", "soda drink" },
  { "🧋", "bubble tea", "boba tea drink" },
  { "🧃", "beverage box", "juice drink" },
  { "🧉", "mate", "drink tea" },
  { "🧊", "ice", "cold frozen cube" },

  -- Travel & Places
  { "🌍", "globe showing Europe-Africa", "world earth globe" },
  { "🌎", "globe showing Americas", "world earth globe" },
  { "🌏", "globe showing Asia-Australia", "world earth globe" },
  { "🌐", "globe with meridians", "world internet web" },
  { "🗺️", "world map", "map travel" },
  { "🏔️", "snow-capped mountain", "mountain snow" },
  { "⛰️", "mountain", "mountain" },
  { "🌋", "volcano", "mountain eruption" },
  { "🗻", "mount fuji", "mountain japan" },
  { "🏕️", "camping", "tent outdoors" },
  { "🏖️", "beach with umbrella", "beach vacation" },
  { "🏜️", "desert", "dry sand" },
  { "🏝️", "desert island", "island tropical" },
  { "🏞️", "national park", "park nature" },
  { "🏟️", "stadium", "sports arena" },
  { "🏛️", "classical building", "building architecture" },
  { "🏗️", "building construction", "construction" },
  { "🧱", "brick", "building wall" },
  { "🪨", "rock", "stone" },
  { "🪵", "wood", "log lumber" },
  { "🛖", "hut", "house" },
  { "🏘️", "houses", "neighborhood" },
  { "🏚️", "derelict house", "abandoned" },
  { "🏠", "house", "home" },
  { "🏡", "house with garden", "home garden" },
  { "🏢", "office building", "building work" },
  { "🏣", "Japanese post office", "mail post" },
  { "🏤", "post office", "mail" },
  { "🏥", "hospital", "medical health" },
  { "🏦", "bank", "money finance" },
  { "🏨", "hotel", "travel accommodation" },
  { "🏩", "love hotel", "hotel" },
  { "🏪", "convenience store", "shop" },
  { "🏫", "school", "education" },
  { "🏬", "department store", "shop mall" },
  { "🏭", "factory", "building industry" },
  { "🏯", "Japanese castle", "castle japan" },
  { "🏰", "castle", "medieval" },
  { "💒", "wedding", "marriage church love" },
  { "🗼", "Tokyo tower", "tower japan" },
  { "🗽", "Statue of Liberty", "liberty usa" },
  { "⛪", "church", "religion" },
  { "🕌", "mosque", "religion islam" },
  { "🛕", "hindu temple", "religion" },
  { "🕍", "synagogue", "religion jewish" },
  { "⛩️", "shinto shrine", "japan shrine" },
  { "🕋", "kaaba", "religion islam mecca" },
  { "⛲", "fountain", "water park" },
  { "⛺", "tent", "camping outdoors" },
  { "🌁", "foggy", "fog" },
  { "🌃", "night with stars", "night city stars" },
  { "🏙️", "cityscape", "city skyline" },
  { "🌄", "sunrise over mountains", "sunrise morning" },
  { "🌅", "sunrise", "morning sun" },
  { "🌆", "cityscape at dusk", "city sunset" },
  { "🌇", "sunset", "evening city" },
  { "🌉", "bridge at night", "bridge night" },
  { "🎠", "carousel horse", "carnival ride" },
  { "🎡", "ferris wheel", "carnival ride" },
  { "🎢", "roller coaster", "theme park ride" },
  { "🚂", "locomotive", "train steam" },
  { "🚃", "railway car", "train" },
  { "🚄", "high-speed train", "train fast bullet" },
  { "🚅", "bullet train", "train fast japan" },
  { "🚆", "train", "rail" },
  { "🚇", "metro", "subway underground" },
  { "🚈", "light rail", "train" },
  { "🚉", "station", "train" },
  { "🚌", "bus", "transit" },
  { "🚍", "oncoming bus", "transit" },
  { "🚎", "trolleybus", "transit" },
  { "🚐", "minibus", "van" },
  { "🚑", "ambulance", "emergency medical" },
  { "🚒", "fire engine", "fire emergency" },
  { "🚓", "police car", "police law" },
  { "🚔", "oncoming police car", "police" },
  { "🚕", "taxi", "cab ride" },
  { "🚖", "oncoming taxi", "cab" },
  { "🚗", "automobile", "car vehicle drive" },
  { "🚘", "oncoming automobile", "car" },
  { "🚙", "sport utility vehicle", "car suv" },
  { "🚚", "delivery truck", "truck delivery" },
  { "🚛", "articulated lorry", "truck semi" },
  { "🚜", "tractor", "farm vehicle" },
  { "🏎️", "racing car", "car race fast formula" },
  { "🏍️", "motorcycle", "bike race" },
  { "🛵", "motor scooter", "scooter vespa" },
  { "🛺", "auto rickshaw", "tuk tuk" },
  { "🚲", "bicycle", "bike cycle" },
  { "🛴", "kick scooter", "scooter" },
  { "🚏", "bus stop", "transit stop" },
  { "🛣️", "motorway", "road highway" },
  { "🛤️", "railway track", "train rail" },
  { "⛽", "fuel pump", "gas station" },
  { "🚨", "police car light", "emergency alert siren" },
  { "🚥", "horizontal traffic light", "traffic" },
  { "🚦", "vertical traffic light", "traffic" },
  { "🚧", "construction", "warning barrier" },
  { "⚓", "anchor", "ship boat" },
  { "⛵", "sailboat", "boat ship sail" },
  { "🚤", "speedboat", "boat fast" },
  { "🛳️", "passenger ship", "cruise ship" },
  { "⛴️", "ferry", "ship boat" },
  { "🛥️", "motor boat", "boat" },
  { "🚢", "ship", "boat ocean" },
  { "✈️", "airplane", "plane fly travel" },
  { "🛩️", "small airplane", "plane" },
  { "🛫", "airplane departure", "takeoff fly" },
  { "🛬", "airplane arrival", "landing fly" },
  { "🪂", "parachute", "sky falling" },
  { "💺", "seat", "chair plane" },
  { "🚁", "helicopter", "fly" },
  { "🚟", "suspension railway", "train" },
  { "🚠", "mountain cableway", "cable car" },
  { "🚡", "aerial tramway", "cable car" },
  { "🛰️", "satellite", "space orbit" },
  { "🚀", "rocket", "space launch" },
  { "🛸", "flying saucer", "ufo alien" },

  -- Sky & Weather
  { "🌌", "milky way", "galaxy space stars" },
  { "⭐", "star", "favorite" },
  { "🌟", "glowing star", "star sparkle shine" },
  { "💫", "shooting star", "dizzy star" },
  { "✨", "sparkles", "sparkle shine glitter magic clean" },
  { "☀️", "sun", "weather sunny bright" },
  { "🌤️", "sun behind small cloud", "weather partly cloudy" },
  { "⛅", "sun behind cloud", "weather cloudy" },
  { "🌥️", "sun behind large cloud", "weather cloudy" },
  { "☁️", "cloud", "weather cloudy" },
  { "🌦️", "sun behind rain cloud", "weather rain" },
  { "🌧️", "cloud with rain", "weather rain" },
  { "⛈️", "cloud with lightning and rain", "weather storm thunder" },
  { "🌩️", "cloud with lightning", "weather storm thunder" },
  { "🌨️", "cloud with snow", "weather snow" },
  { "❄️", "snowflake", "snow winter cold" },
  { "☃️", "snowman", "snow winter" },
  { "⛄", "snowman without snow", "snow winter" },
  { "🌪️", "tornado", "weather storm" },
  { "🌫️", "fog", "weather" },
  { "🌬️", "wind face", "weather wind blow" },
  { "🌈", "rainbow", "colors weather pride" },
  { "☂️", "umbrella", "rain weather" },
  { "☔", "umbrella with rain drops", "rain weather" },
  { "⚡", "high voltage", "lightning electricity thunder zap" },
  { "🔥", "fire", "hot flame burn lit" },
  { "💧", "droplet", "water rain tear" },
  { "🌊", "water wave", "ocean sea surf wave" },

  -- Activities & Sports
  { "🎃", "jack-o-lantern", "halloween pumpkin" },
  { "🎄", "Christmas tree", "christmas holiday tree" },
  { "🎆", "fireworks", "celebrate new year" },
  { "🎇", "sparkler", "fireworks celebrate" },
  { "🧨", "firecracker", "explosive celebrate" },
  { "✨", "sparkles", "shine magic clean" },
  { "🎈", "balloon", "party celebrate birthday" },
  { "🎉", "party popper", "celebrate congratulations tada" },
  { "🎊", "confetti ball", "celebrate party" },
  { "🎋", "tanabata tree", "japanese" },
  { "🎍", "pine decoration", "japanese new year" },
  { "🎎", "Japanese dolls", "japanese" },
  { "🎏", "carp streamer", "japanese" },
  { "🎐", "wind chime", "japanese" },
  { "🎑", "moon viewing ceremony", "moon japanese" },
  { "🧧", "red envelope", "chinese money gift" },
  { "🎀", "ribbon", "gift bow pink" },
  { "🎁", "wrapped gift", "present birthday gift" },
  { "🎗️", "reminder ribbon", "awareness" },
  { "🎟️", "admission tickets", "ticket event" },
  { "🎫", "ticket", "event admission" },
  { "🎖️", "military medal", "medal award" },
  { "🏆", "trophy", "winner award cup" },
  { "🏅", "sports medal", "medal award" },
  { "🥇", "1st place medal", "gold first winner" },
  { "🥈", "2nd place medal", "silver second" },
  { "🥉", "3rd place medal", "bronze third" },
  { "⚽", "soccer ball", "football sport" },
  { "⚾", "baseball", "sport ball" },
  { "🥎", "softball", "sport ball" },
  { "🏀", "basketball", "sport ball" },
  { "🏐", "volleyball", "sport ball" },
  { "🏈", "american football", "sport ball" },
  { "🏉", "rugby football", "sport ball" },
  { "🎾", "tennis", "sport ball racquet" },
  { "🥏", "flying disc", "frisbee sport" },
  { "🎳", "bowling", "sport" },
  { "🏏", "cricket game", "sport bat" },
  { "🏑", "field hockey", "sport" },
  { "🏒", "ice hockey", "sport" },
  { "🥍", "lacrosse", "sport" },
  { "🏓", "ping pong", "table tennis sport" },
  { "🏸", "badminton", "sport" },
  { "🥊", "boxing glove", "sport fight" },
  { "🥋", "martial arts uniform", "karate judo" },
  { "🥅", "goal net", "sport" },
  { "⛳", "flag in hole", "golf sport" },
  { "⛸️", "ice skate", "skating sport winter" },
  { "🎣", "fishing pole", "fishing sport" },
  { "🤿", "diving mask", "dive snorkel swim" },
  { "🎽", "running shirt", "sport marathon" },
  { "🎿", "skis", "skiing sport winter" },
  { "🛷", "sled", "winter sport" },
  { "🥌", "curling stone", "sport winter" },
  { "🎯", "bullseye", "target dart aim" },
  { "🪀", "yo-yo", "toy" },
  { "🪁", "kite", "fly toy wind" },
  { "🎱", "pool 8 ball", "billiards sport" },
  { "🔮", "crystal ball", "fortune magic" },
  { "🪄", "magic wand", "magic wizard" },
  { "🧿", "nazar amulet", "evil eye protect" },
  { "🎮", "video game", "game controller play" },
  { "🕹️", "joystick", "game arcade" },
  { "🎰", "slot machine", "gamble casino" },
  { "🎲", "game die", "dice random" },
  { "🧩", "puzzle piece", "puzzle jigsaw" },
  { "🧸", "teddy bear", "toy stuffed" },
  { "🪆", "nesting dolls", "matryoshka russian" },
  { "♠️", "spade suit", "cards poker" },
  { "♥️", "heart suit", "cards poker" },
  { "♦️", "diamond suit", "cards poker" },
  { "♣️", "club suit", "cards poker" },
  { "♟️", "chess pawn", "chess game" },
  { "🃏", "joker", "cards wildcard" },
  { "🀄", "mahjong red dragon", "game chinese" },
  { "🎴", "flower playing cards", "game japanese" },
  { "🎭", "performing arts", "theater drama masks" },
  { "🖼️", "framed picture", "art painting" },
  { "🎨", "artist palette", "art paint color" },
  { "🧵", "thread", "sewing needle" },
  { "🪡", "sewing needle", "sewing thread" },
  { "🧶", "yarn", "knitting crochet" },
  { "🪢", "knot", "tie rope" },

  -- Objects
  { "👓", "glasses", "eyeglasses spectacles" },
  { "🕶️", "sunglasses", "cool shades" },
  { "🥽", "goggles", "eye protection" },
  { "🥼", "lab coat", "science doctor" },
  { "🦺", "safety vest", "construction" },
  { "👔", "necktie", "tie formal business" },
  { "👕", "t-shirt", "shirt clothes" },
  { "👖", "jeans", "pants clothes denim" },
  { "🧣", "scarf", "winter clothes" },
  { "🧤", "gloves", "winter hands" },
  { "🧥", "coat", "jacket winter clothes" },
  { "🧦", "socks", "clothes" },
  { "👗", "dress", "clothes fashion" },
  { "👘", "kimono", "japanese clothes" },
  { "🥻", "sari", "indian clothes" },
  { "🩱", "one-piece swimsuit", "swim clothes" },
  { "🩲", "briefs", "underwear clothes" },
  { "🩳", "shorts", "clothes summer" },
  { "👙", "bikini", "swim beach clothes" },
  { "👚", "woman's clothes", "clothes" },
  { "👛", "purse", "bag money" },
  { "👜", "handbag", "bag fashion" },
  { "👝", "clutch bag", "bag" },
  { "🛍️", "shopping bags", "shop buy" },
  { "🎒", "backpack", "bag school" },
  { "🩴", "thong sandal", "flip flop shoe" },
  { "👞", "man's shoe", "shoe formal" },
  { "👟", "running shoe", "sneaker shoe sport" },
  { "🥾", "hiking boot", "shoe boot outdoor" },
  { "🥿", "flat shoe", "shoe ballet" },
  { "👠", "high-heeled shoe", "heel shoe fashion" },
  { "👡", "woman's sandal", "shoe" },
  { "🩰", "ballet shoes", "dance" },
  { "👢", "woman's boot", "shoe boot" },
  { "👑", "crown", "king queen royal" },
  { "👒", "woman's hat", "hat fashion" },
  { "🎩", "top hat", "hat formal classy" },
  { "🎓", "graduation cap", "education school graduate" },
  { "🧢", "billed cap", "cap hat baseball" },
  { "🪖", "military helmet", "army soldier" },
  { "⛑️", "rescue worker's helmet", "safety" },
  { "💄", "lipstick", "makeup beauty" },
  { "💍", "ring", "jewelry wedding diamond" },
  { "💎", "gem stone", "diamond jewel precious" },
  { "🔇", "muted speaker", "mute sound silence" },
  { "🔈", "speaker low volume", "sound" },
  { "🔉", "speaker medium volume", "sound" },
  { "🔊", "speaker high volume", "sound loud" },
  { "📢", "loudspeaker", "announcement megaphone" },
  { "📣", "megaphone", "announcement cheer" },
  { "📯", "postal horn", "instrument" },
  { "🔔", "bell", "notification alert ring" },
  { "🔕", "bell with slash", "mute notification silent" },
  { "🎵", "musical note", "music note" },
  { "🎶", "musical notes", "music notes melody" },
  { "🎙️", "studio microphone", "mic podcast record" },
  { "🎚️", "level slider", "music audio" },
  { "🎛️", "control knobs", "music audio" },
  { "🎤", "microphone", "mic sing karaoke" },
  { "🎧", "headphone", "headphones music audio" },
  { "📻", "radio", "music broadcast" },
  { "🎷", "saxophone", "music jazz instrument" },
  { "🪗", "accordion", "music instrument" },
  { "🎸", "guitar", "music rock instrument" },
  { "🎹", "musical keyboard", "piano music instrument" },
  { "🎺", "trumpet", "music instrument brass" },
  { "🎻", "violin", "music instrument strings" },
  { "🪕", "banjo", "music instrument country" },
  { "🥁", "drum", "music instrument beat" },
  { "🪘", "long drum", "music instrument" },

  -- Technology & Devices
  { "📱", "mobile phone", "phone cell smartphone" },
  { "📲", "mobile phone with arrow", "call phone" },
  { "☎️", "telephone", "phone call landline" },
  { "📞", "telephone receiver", "phone call" },
  { "📟", "pager", "beeper" },
  { "📠", "fax machine", "fax" },
  { "🔋", "battery", "power energy charge" },
  { "🔌", "electric plug", "power cord" },
  { "💻", "laptop", "computer pc mac" },
  { "🖥️", "desktop computer", "computer pc monitor" },
  { "🖨️", "printer", "print computer" },
  { "⌨️", "keyboard", "computer type" },
  { "🖱️", "computer mouse", "mouse click" },
  { "🖲️", "trackball", "mouse" },
  { "💽", "computer disk", "floppy save" },
  { "💾", "floppy disk", "save old disk" },
  { "💿", "optical disk", "cd dvd" },
  { "📀", "dvd", "disk" },
  { "🧮", "abacus", "calculator math" },
  { "🎥", "movie camera", "film camera" },
  { "🎞️", "film frames", "movie film" },
  { "📽️", "film projector", "movie" },
  { "📺", "television", "tv screen" },
  { "📷", "camera", "photo picture" },
  { "📸", "camera with flash", "photo picture" },
  { "📹", "video camera", "record" },
  { "📼", "videocassette", "vhs tape" },
  { "🔍", "magnifying glass tilted left", "search find zoom" },
  { "🔎", "magnifying glass tilted right", "search find zoom" },
  { "🕯️", "candle", "light flame" },
  { "💡", "light bulb", "idea bright" },
  { "🔦", "flashlight", "light torch" },
  { "🏮", "red paper lantern", "lantern light" },
  { "🪔", "diya lamp", "light oil" },

  -- Office & Documents
  { "📔", "notebook with decorative cover", "journal" },
  { "📕", "closed book", "book red" },
  { "📖", "open book", "book read" },
  { "📗", "green book", "book" },
  { "📘", "blue book", "book" },
  { "📙", "orange book", "book" },
  { "📚", "books", "library study read" },
  { "📓", "notebook", "write" },
  { "📒", "ledger", "notes" },
  { "📃", "page with curl", "document paper" },
  { "📜", "scroll", "document old" },
  { "📄", "page facing up", "document paper file" },
  { "📰", "newspaper", "news paper" },
  { "🗞️", "rolled-up newspaper", "news paper" },
  { "📑", "bookmark tabs", "bookmark" },
  { "🔖", "bookmark", "save mark" },
  { "🏷️", "label", "tag" },
  { "💰", "money bag", "money dollar rich" },
  { "🪙", "coin", "money" },
  { "💴", "yen banknote", "money japan" },
  { "💵", "dollar banknote", "money usa" },
  { "💶", "euro banknote", "money europe" },
  { "💷", "pound banknote", "money uk" },
  { "💸", "money with wings", "money flying spend" },
  { "💳", "credit card", "money card pay" },
  { "🧾", "receipt", "money buy" },
  { "✉️", "envelope", "mail letter email" },
  { "📧", "e-mail", "email message" },
  { "📨", "incoming envelope", "mail receive" },
  { "📩", "envelope with arrow", "mail send" },
  { "📤", "outbox tray", "mail send upload" },
  { "📥", "inbox tray", "mail receive download" },
  { "📦", "package", "box delivery shipping" },
  { "📫", "closed mailbox with raised flag", "mail" },
  { "📪", "closed mailbox with lowered flag", "mail" },
  { "📬", "open mailbox with raised flag", "mail" },
  { "📭", "open mailbox with lowered flag", "mail" },
  { "🗳️", "ballot box with ballot", "vote election" },
  { "✏️", "pencil", "write draw" },
  { "✒️", "black nib", "pen write" },
  { "🖊️", "pen", "write" },
  { "🖋️", "fountain pen", "write" },
  { "🖌️", "paintbrush", "art paint" },
  { "🖍️", "crayon", "art draw color" },
  { "📝", "memo", "note write" },
  { "📁", "file folder", "folder directory" },
  { "📂", "open file folder", "folder directory" },
  { "🗂️", "card index dividers", "organize" },
  { "📅", "calendar", "date schedule" },
  { "📆", "tear-off calendar", "date schedule" },
  { "🗒️", "spiral notepad", "note write" },
  { "🗓️", "spiral calendar", "date schedule" },
  { "📇", "card index", "contacts" },
  { "📈", "chart increasing", "graph growth up stock" },
  { "📉", "chart decreasing", "graph decline down stock" },
  { "📊", "bar chart", "graph statistics data" },
  { "📋", "clipboard", "paste copy" },
  { "📌", "pushpin", "pin location" },
  { "📍", "round pushpin", "pin location map" },
  { "📎", "paperclip", "attach" },
  { "🖇️", "linked paperclips", "attach" },
  { "📏", "straight ruler", "measure" },
  { "📐", "triangular ruler", "measure" },
  { "✂️", "scissors", "cut" },
  { "🗃️", "card file box", "file organize" },
  { "🗄️", "file cabinet", "file organize" },
  { "🗑️", "wastebasket", "trash delete garbage" },

  -- Locks & Keys
  { "🔒", "locked", "lock security" },
  { "🔓", "unlocked", "lock open" },
  { "🔏", "locked with pen", "lock privacy" },
  { "🔐", "locked with key", "lock security" },
  { "🔑", "key", "lock password" },
  { "🗝️", "old key", "lock antique" },

  -- Tools
  { "🔨", "hammer", "tool build" },
  { "🪓", "axe", "tool chop" },
  { "⛏️", "pick", "tool mine" },
  { "⚒️", "hammer and pick", "tool build" },
  { "🛠️", "hammer and wrench", "tool fix settings" },
  { "🗡️", "dagger", "weapon knife sword" },
  { "⚔️", "crossed swords", "weapon fight battle" },
  { "🔫", "water pistol", "gun weapon" },
  { "🪃", "boomerang", "throw return" },
  { "🏹", "bow and arrow", "weapon archery" },
  { "🛡️", "shield", "protect defense" },
  { "🪚", "carpentry saw", "tool wood" },
  { "🔧", "wrench", "tool fix settings" },
  { "🪛", "screwdriver", "tool fix" },
  { "🔩", "nut and bolt", "tool fix hardware" },
  { "⚙️", "gear", "settings cog config" },
  { "🗜️", "clamp", "tool compress" },
  { "⚖️", "balance scale", "justice law weight" },
  { "🦯", "white cane", "blind accessibility" },
  { "🔗", "link", "chain url hyperlink" },
  { "⛓️", "chains", "chain lock" },
  { "🪝", "hook", "catch fish" },
  { "🧰", "toolbox", "tool fix" },
  { "🧲", "magnet", "attract" },
  { "🪜", "ladder", "climb step" },

  -- Science & Medical
  { "⚗️", "alembic", "science chemistry" },
  { "🧪", "test tube", "science experiment" },
  { "🧫", "petri dish", "science biology" },
  { "🧬", "dna", "science biology genetics" },
  { "🔬", "microscope", "science zoom" },
  { "🔭", "telescope", "science astronomy" },
  { "📡", "satellite antenna", "communication satellite" },
  { "💉", "syringe", "medical needle vaccine" },
  { "🩸", "drop of blood", "blood medical" },
  { "💊", "pill", "medicine drug health" },
  { "🩹", "adhesive bandage", "bandaid medical" },
  { "🩺", "stethoscope", "medical doctor" },

  -- Symbols & Signs
  { "🏧", "ATM sign", "bank money" },
  { "🚮", "litter in bin sign", "trash garbage" },
  { "🚰", "potable water", "water drink" },
  { "♿", "wheelchair symbol", "disabled accessibility" },
  { "🚹", "men's room", "restroom male" },
  { "🚺", "women's room", "restroom female" },
  { "🚻", "restroom", "toilet bathroom" },
  { "🚼", "baby symbol", "baby changing" },
  { "🚾", "water closet", "toilet restroom" },
  { "🛂", "passport control", "travel border" },
  { "🛃", "customs", "travel border" },
  { "🛄", "baggage claim", "travel airport" },
  { "🛅", "left luggage", "travel storage" },
  { "⚠️", "warning", "danger caution alert" },
  { "🚸", "children crossing", "school" },
  { "⛔", "no entry", "stop prohibited forbidden" },
  { "🚫", "prohibited", "forbidden stop no" },
  { "🚳", "no bicycles", "prohibited" },
  { "🚭", "no smoking", "prohibited" },
  { "🚯", "no littering", "prohibited" },
  { "🚱", "non-potable water", "water" },
  { "🚷", "no pedestrians", "prohibited" },
  { "📵", "no mobile phones", "phone prohibited" },
  { "🔞", "no one under eighteen", "age restricted adult" },
  { "☢️", "radioactive", "nuclear danger" },
  { "☣️", "biohazard", "danger toxic" },
  { "⬆️", "up arrow", "arrow up" },
  { "↗️", "up-right arrow", "arrow direction" },
  { "➡️", "right arrow", "arrow right" },
  { "↘️", "down-right arrow", "arrow direction" },
  { "⬇️", "down arrow", "arrow down" },
  { "↙️", "down-left arrow", "arrow direction" },
  { "⬅️", "left arrow", "arrow left" },
  { "↖️", "up-left arrow", "arrow direction" },
  { "↕️", "up-down arrow", "arrow vertical" },
  { "↔️", "left-right arrow", "arrow horizontal" },
  { "↩️", "right arrow curving left", "arrow return undo back" },
  { "↪️", "left arrow curving right", "arrow forward redo" },
  { "⤴️", "right arrow curving up", "arrow" },
  { "⤵️", "right arrow curving down", "arrow" },
  { "🔃", "clockwise vertical arrows", "arrow rotate refresh" },
  { "🔄", "counterclockwise arrows button", "arrow rotate refresh sync" },
  { "🔙", "BACK arrow", "arrow back return" },
  { "🔚", "END arrow", "arrow end" },
  { "🔛", "ON! arrow", "arrow on" },
  { "🔜", "SOON arrow", "arrow soon" },
  { "🔝", "TOP arrow", "arrow top" },
  { "✅", "check mark button", "yes done complete approve green" },
  { "☑️", "check box with check", "yes done checkbox" },
  { "✔️", "check mark", "yes done correct" },
  { "❌", "cross mark", "no wrong delete remove" },
  { "❎", "cross mark button", "no wrong" },
  { "➕", "plus", "add math" },
  { "➖", "minus", "subtract math" },
  { "➗", "divide", "division math" },
  { "✖️", "multiply", "multiplication math" },
  { "♾️", "infinity", "forever unlimited" },
  { "❗", "exclamation mark", "important alert" },
  { "❓", "question mark", "help what confused" },
  { "❕", "white exclamation mark", "important" },
  { "❔", "white question mark", "help what" },
  { "‼️", "double exclamation mark", "important surprise" },
  { "⁉️", "exclamation question mark", "surprise confused" },
  { "〰️", "wavy dash", "line" },
  { "💱", "currency exchange", "money forex" },
  { "💲", "heavy dollar sign", "money dollar" },
  { "⚕️", "medical symbol", "health doctor hospital" },
  { "♻️", "recycling symbol", "recycle environment green" },
  { "⚜️", "fleur-de-lis", "french" },
  { "🔰", "Japanese symbol for beginner", "new beginner" },
  { "🔱", "trident emblem", "weapon poseidon" },
  { "⭕", "hollow red circle", "circle" },
  { "🔴", "red circle", "circle red" },
  { "🟠", "orange circle", "circle orange" },
  { "🟡", "yellow circle", "circle yellow" },
  { "🟢", "green circle", "circle green" },
  { "🔵", "blue circle", "circle blue" },
  { "🟣", "purple circle", "circle purple" },
  { "🟤", "brown circle", "circle brown" },
  { "⚫", "black circle", "circle black" },
  { "⚪", "white circle", "circle white" },
  { "🟥", "red square", "square red" },
  { "🟧", "orange square", "square orange" },
  { "🟨", "yellow square", "square yellow" },
  { "🟩", "green square", "square green" },
  { "🟦", "blue square", "square blue" },
  { "🟪", "purple square", "square purple" },
  { "🟫", "brown square", "square brown" },
  { "⬛", "black large square", "square black" },
  { "⬜", "white large square", "square white" },
  { "🔶", "large orange diamond", "diamond orange" },
  { "🔷", "large blue diamond", "diamond blue" },
  { "🔸", "small orange diamond", "diamond orange" },
  { "🔹", "small blue diamond", "diamond blue" },
  { "🔺", "red triangle pointed up", "triangle red" },
  { "🔻", "red triangle pointed down", "triangle red" },
  { "💠", "diamond with a dot", "diamond" },
  { "🔘", "radio button", "button circle" },
  { "🔳", "white square button", "button square" },
  { "🔲", "black square button", "button square" },

  -- Flags (selection)
  { "🏁", "chequered flag", "flag race finish" },
  { "🚩", "triangular flag", "flag red" },
  { "🎌", "crossed flags", "flag japan" },
  { "🏴", "black flag", "flag" },
  { "🏳️", "white flag", "flag surrender" },
  { "🏳️‍🌈", "rainbow flag", "pride lgbtq flag" },
  { "🏳️‍⚧️", "transgender flag", "trans pride flag" },
  { "🏴‍☠️", "pirate flag", "pirate skull flag" },

  -- Math & Misc Symbols
  { "🔀", "shuffle tracks button", "shuffle random" },
  { "🔁", "repeat button", "loop repeat" },
  { "🔂", "repeat single button", "loop repeat one" },
  { "▶️", "play button", "play start" },
  { "⏩", "fast-forward button", "forward fast" },
  { "⏭️", "next track button", "next skip" },
  { "⏯️", "play or pause button", "play pause" },
  { "◀️", "reverse button", "backward reverse" },
  { "⏪", "fast reverse button", "rewind" },
  { "⏮️", "last track button", "previous back" },
  { "⏸️", "pause button", "pause stop" },
  { "⏹️", "stop button", "stop" },
  { "⏺️", "record button", "record" },
  { "⏏️", "eject button", "eject" },
  { "🔅", "dim button", "brightness low" },
  { "🔆", "bright button", "brightness high" },
  { "📶", "antenna bars", "signal wifi" },
  { "📳", "vibration mode", "phone vibrate" },
  { "📴", "mobile phone off", "phone off" },

  -- Additional useful symbols
  { "♀️", "female sign", "woman female gender" },
  { "♂️", "male sign", "man male gender" },
  { "⚧️", "transgender symbol", "trans gender" },
  { "🔣", "input symbols", "symbols characters" },
  { "ℹ️", "information", "info help" },
  { "🆎", "AB button", "blood type" },
  { "🆑", "CL button", "clear" },
  { "🆘", "SOS button", "help emergency" },
  { "🆔", "ID button", "identity" },
  { "Ⓜ️", "circled M", "metro" },
  { "🆕", "NEW button", "new" },
  { "🆖", "NG button", "no good" },
  { "🅾️", "O button", "blood type" },
  { "🆗", "OK button", "okay" },
  { "🅿️", "P button", "parking" },
  { "🆚", "VS button", "versus" },
  { "🈁", "Japanese here button", "japanese" },
  { "🈂️", "Japanese service charge button", "japanese" },
  { "🔠", "input latin uppercase", "abc letters" },
  { "🔡", "input latin lowercase", "abc letters" },
  { "🔢", "input numbers", "123 numbers" },
  { "🔤", "input latin letters", "abc letters" },
  { "🅰️", "A button", "blood type letter" },
  { "🅱️", "B button", "blood type letter" },
  { "#️⃣", "keycap #", "hash number" },
  { "*️⃣", "keycap *", "star asterisk" },
  { "0️⃣", "keycap 0", "zero number" },
  { "1️⃣", "keycap 1", "one number" },
  { "2️⃣", "keycap 2", "two number" },
  { "3️⃣", "keycap 3", "three number" },
  { "4️⃣", "keycap 4", "four number" },
  { "5️⃣", "keycap 5", "five number" },
  { "6️⃣", "keycap 6", "six number" },
  { "7️⃣", "keycap 7", "seven number" },
  { "8️⃣", "keycap 8", "eight number" },
  { "9️⃣", "keycap 9", "nine number" },
  { "🔟", "keycap 10", "ten number" },
  { "©️", "copyright", "copy legal" },
  { "®️", "registered", "trademark legal" },
  { "™️", "trade mark", "trademark brand" },
}

--- Open the emoji telescope picker
function M.pick()
  local ok = pcall(require, 'telescope')
  if not ok then
    vim.notify('telescope.nvim is required for the emoji picker', vim.log.levels.ERROR)
    return
  end

  local pickers = require('telescope.pickers')
  local finders = require('telescope.finders')
  local conf = require('telescope.config').values
  local actions = require('telescope.actions')
  local action_state = require('telescope.actions.state')
  local entry_display = require('telescope.pickers.entry_display')

  -- Build the displayer: emoji column + name column
  local displayer = entry_display.create({
    separator = ' ',
    items = {
      { width = 4 },  -- emoji
      { remaining = true }, -- name + keywords
    },
  })

  local make_display = function(entry)
    return displayer({
      entry.value.emoji,
      entry.value.name,
    })
  end

  pickers.new({}, {
    prompt_title = 'Noto Emoji / Icons',
    finder = finders.new_table({
      results = emojis,
      entry_maker = function(item)
        -- Searchable text combines name and keywords
        local ordinal = item[1] .. ' ' .. item[2] .. ' ' .. item[3]
        return {
          value = { emoji = item[1], name = item[2], keywords = item[3] },
          display = make_display,
          ordinal = ordinal,
        }
      end,
    }),
    sorter = conf.generic_sorter({}),
    attach_mappings = function(prompt_bufnr, _)
      actions.select_default:replace(function()
        actions.close(prompt_bufnr)
        local selection = action_state.get_selected_entry()
        if selection then
          -- Insert emoji at cursor position
          local emoji = selection.value.emoji
          local pos = vim.api.nvim_win_get_cursor(0)
          local line = vim.api.nvim_get_current_line()
          local row = pos[1]
          local col = pos[2]
          local before = line:sub(1, col)
          local after = line:sub(col + 1)
          vim.api.nvim_set_current_line(before .. emoji .. after)
          -- Move cursor after inserted emoji
          vim.api.nvim_win_set_cursor(0, { row, col + #emoji })
        end
      end)
      return true
    end,
  }):find()
end

return M
